(org-babel-load-file "~/.emacs.d/readme.org")
;; Set initial frame size and position
;(defun my/set-initial-frame ()
;  (let* ((base-factor 0.70)
;	(a-width (* (display-pixel-width) base-factor))
;        (a-height (* (display-pixel-height) base-factor))
;        (a-left (truncate (/ (- (display-pixel-width) a-width) 2)))
;	(a-top (truncate (/ (- (display-pixel-height) a-height) 2))))
;    (set-frame-position (selected-frame) a-left a-top)
;    (set-frame-size (selected-frame) (truncate a-width)  (truncate a-height) t)))
;(setq frame-resize-pixelwise t)
;(my/set-initial-frame)
