#+Title: Jacob's Emacs Configuration
#+Author: Jacob Duijzer
#+Description: 
#+Startup: showeverything
#+Options: toc:2

* Table Of Contents :TOC_4:
- [[#global-emacs-configuration][Global Emacs Configuration]]
  - [[#evil-mode][Evil mode]]
  - [[#general-keybindings][General Keybindings]]
  - [[#set-theme][Set Theme]]
  - [[#nerd-icons][Nerd Icons]]
  - [[#zooming-inout][Zooming In/Out]]
  - [[#modeline][Modeline]]
  - [[#dashboard][Dashboard]]
  - [[#dashboard-in-emacsclient][Dashboard in Emacsclient]]
- [[#org][Org]]
  - [[#org-mode][Org mode]]
  - [[#org-modern][Org Modern]]
  - [[#default-file-actions][Default file actions]]
    - [[#][]]
  - [[#org-definitions][Org definitions]]
  - [[#auto-update-images][Auto update images]]
  - [[#agenda][Agenda]]
  - [[#alerts--notifications][Alerts / Notifications]]
  - [[#enabling-table-of-contents][Enabling Table of Contents]]
  - [[#org-bullets-v2][Org Bullets v2]]
  - [[#source-code-block-tag-expansion][Source Code Block Tag Expansion]]
  - [[#org-roam][Org Roam]]
  - [[#search-org-roam][Search org-roam]]
- [[#other-packages][Other packages]]
  - [[#consult][Consult]]
  - [[#oliveti][Oliveti]]
  - [[#blogging-with-hugo][Blogging with Hugo]]
  - [[#magit][Magit]]
  - [[#projectile][Projectile]]
  - [[#company][Company]]
  - [[#ivy-counsel][Ivy (counsel)]]
  - [[#diminish][DIMINISH]]
  - [[#which-key][WHICH-KEY]]
  - [[#plantuml][PlantUML]]
  - [[#gherkin][Gherkin]]
  - [[#yasnippet][YASnippet]]
  - [[#spell-checking][Spell checking]]
  - [[#runtime-performance][Runtime Performance]]
  - [[#commenting-lines][Commenting lines]]
  - [[#webjump][Webjump]]
- [[#trying-out][Trying out]]
  - [[#eat-terminal-emulation][Eat (terminal emulation)]]

* Global Emacs Configuration

** Evil mode
Evil is an extensible vi/vim layer for Emacs.  Because…let’s face it.  The Vim keybindings are just plain better.
Note: To paste without copy (yank) selected text use P (shift P evil-paste-before), because default is evil-paste-after.
You can toggle evil mode with ctrl z (emacs-mode)

#+BEGIN_SRC emacs-lisp
(use-package evil
    :init ;; tweak evil's configuration before loading it
    (setq evil-want-keybinding nil) ;; Disable evil bindings in other modes (It's not consistent and not good)
    (setq evil-want-C-u-scroll t) ;; Set  C-u to scrool up
    (setq evil-want-C-i-jump nil) ;; Disables C-i jump
    (setq evil-undo-system 'undo-redo) ;; C-r to redo
    (setq org-return-follows-link  t) ;; Sets RETURN key in org-mode to follow links
    (evil-mode))
(use-package evil-collection
    :after evil
    :config
    ;; Setting where to use evil-collection
    (setq evil-collection-mode-list '(dired ibuffer magiti dashboard))
    (evil-collection-init))
;; Unmap keys in 'evil-maps. If not done, (setq org-return-follows-link t) will not work
(with-eval-after-load 'evil-maps
    (define-key evil-motion-state-map (kbd "SPC") nil)
    (define-key evil-motion-state-map (kbd "RET") nil)
    (define-key evil-motion-state-map (kbd "TAB") nil))
#+END_SRC

** General Keybindings
General is a keybinding framework to set keybindings easily.
The Leader key is what you will press when you want to access your keybindings (Space + . Find file).
To search and replace start use query-replace-regexp one by one (SPACE to replace n to skip meta/alt ctrl %) [[https://stackoverflow.com/questions/270930/using-emacs-to-recursively-find-and-replace-in-text-files-not-already-open][Source]]
#+begin_src emacs-lisp
(use-package general
  :config
  (general-evil-setup)
  ;; set up 'SPC' as the global leader key
  (general-create-definer start/leader-keys
    :states '(normal insert visual emacs)
    :keymaps 'override
    :prefix "SPC" ;; set leader
    :global-prefix "C-SPC") ;; access leader in insert mode

  (start/leader-keys
    "." '(find-file :wk "Find file")
    "TAB" '(comment-line :wk "Comment lines")
    "p" '(projectile-command-map :wk "Projectile command map"))

  (start/leader-keys
	"a" '(org-agenda :wk "Show Agenda"))

  (start/leader-keys
    "f" '(:ignore t :wk "Find")
    "f c" '((lambda () (interactive) (find-file "~/.config/emacs/config.org")) :wk "Edit emacs config")
    "f r" '(counsel-recentf :wk "Recent files"))

  (start/leader-keys
    "b" '(:ignore t :wk "Buffer Bookmarks")
    "b b" '(counsel-switch-buffer :wk "Switch buffer")
    ;;"b b" '(ivy-switch-buffer :wk "Switch buffer")
    "b k" '(kill-this-buffer :wk "Kill this buffer")
    "b i" '(ibuffer :wk "Ibuffer")
    "b n" '(next-buffer :wk "Next buffer")
    "b p" '(previous-buffer :wk "Previous buffer")
    "b r" '(revert-buffer :wk "Reload buffer")
    "b R" '(rename-buffer :wk "Rename buffer")
    "b j" '(bookmark-jump :wk "Bookmark jump"))

  (start/leader-keys
    "d" '(:ignore t :wk "Dired")
    "d v" '(dired :wk "Open dired")
    "d j" '(dired-jump :wk "Dired jump to current"))

  (start/leader-keys
    "g" '(:ignore t :wk "Git")
    "g g" '(magit-status :wk "Magit status"))

  (start/leader-keys
    "h" '(:ignore t :wk "Help")
    "h c" '(company-manual-begin :wk "Company completion at point")
    "h r" '((lambda () (interactive)
              (load-file "~/.config/emacs/init.el"))
            :wk "Reload emacs config"))

  (start/leader-keys
	"r" '(:ignore t :wk "Org-Roam")
	"r t" '(org-roam-dailies-capture-today :wk "Capture Today")
	"r f" '(org-roam-node-find :wk "Find node")
	"r i" '(org-roam-node-find :wk "Insert node")
	"r j t" '(org-roam-dailies-capture-today :wk "Journal for today")
	"r j y" '(org-roam-dailies-capture-yesterday :wk "Journal for yesterday")
	"r j m" '(org-roam-dailies-capture-tomorrow :wk "Journal for tomorrow")
	"r v t" '(org-roam-dailies-goto-today :wk "View journal for today")
	"r v y" '(org-roam-dailies-goto-yesterday :wk "View journal for yesterday")
	"r v m" '(org-roam-dailies-goto-tomorrow :wk "View journal for tomorrow"))
  
  (start/leader-keys
    "s" '(:ignore t :wk "Show")
    "s e" '(eat :wk "Show Eat"))

  (start/leader-keys
    "t" '(:ignore t :wk "Toggle")
    "t l" '(display-line-numbers-mode :wk "Toggle line numbers")
    "t t" '(visual-line-mode :wk "Toggle truncated lines (wrap)"))
  
  (start/leader-keys
	"w" '(:ignore t :wk "Screen size & position")
	"w c" '(my/frame-recenter :wk "Center window")
	"w m" '(:ignore t :wk "Move screen")
	"w mc" '((lambda () (interactive)(my/frame-move 0.5 0.5)) :wk "Move to the center")
  	"w mr" '((lambda () (interactive)(my/frame-move 0.98 0.5)) :wk "Move to the right")
  	"w ml" '((lambda () (interactive)(my/frame-move 0 0.5)) :wk "Move to the right")
	"w s" '(:ignore t :wk "Window Split")
	"w sb" '((lambda () (interactive)(split-window-below)) :wk "Split window below")
	"w sr" '((lambda () (interactive)(split-window-right)) :wk "Split window right")
))

#+END_SRC

** Set Theme

#+begin_src emacs-lisp
(use-package modus-themes
  :custom
  (modus-themes-italic-constructs t)
  (modus-themes-bold-constructs t)
  (modus-themes-mixed-fonts t)
  (modus-themes-headings '((1 . (1.5))
                           (2 . (1.3))
                           (t . (1.1))))
  (modus-themes-to-toggle
   '(modus-operandi modus-vivendi))
  :bind
  (("C-c w m" . modus-themes-toggle)
   ("C-c w M" . modus-themes-select))
  :init
  (load-theme 'modus-vivendi :no-confirm))
#+end_src

** Nerd Icons
For icons and more helpful ui.
This is an icon set that can be used with dired, ibuffer and other Emacs programs.

Don't forget to use nerd-icons-install-fonts.

We use Nerd icons because it has more, better icons and all-the-icons only supports GUI.
While nerd-icons supports both GUI and TUI.

#+BEGIN_SRC emacs-lisp
	(require 'all-the-icons)
#+END_SRC

#+begin_src emacs-lisp
	(use-package nerd-icons
		:if (display-graphic-p))

	(use-package nerd-icons-dired
		:hook (dired-mode . (lambda () (nerd-icons-dired-mode t))))

	(use-package nerd-icons-ibuffer
		:hook (ibuffer-mode . nerd-icons-ibuffer-mode))
#+end_src

#+RESULTS:
| nerd-icons-ibuffer-mode |

** Zooming In/Out
You can use the bindings CTRL plus =/- for zooming in/out.  You can also use CTRL plus the mouse wheel for zooming in/out.
#+begin_src emacs-lisp
(global-set-key (kbd "C-+") 'text-scale-increase)
(global-set-key (kbd "C--") 'text-scale-decrease)
(global-set-key (kbd "C-0") 'text-scale-set)
(global-set-key (kbd "<C-wheel-up>") 'text-scale-increase)
(global-set-key (kbd "<C-wheel-down>") 'text-scale-decrease)
#+end_src

#+RESULTS:
: text-scale-decrease

** Modeline
Replace the default modeline with a pretier more useful.

#+BEGIN_SRC emacs-lisp
(use-package telephone-line)
(telephone-line-mode 1)
#+END_SRC

** Dashboard 

#+begin_src emacs-lisp
(use-package dashboard
    :init      ;; tweak dashboard config before loading it
    (setq dashboard-set-heading-icons t)
    (setq dashboard-set-file-icons t)
    (setq dashboard-set-init-info t)
    ;;(setq dashboard-banner-logo-title "Emacs Is More Than A Text Editor!")
    ;;(setq dashboard-startup-banner 'logo) ;; use standard emacs logo as banner
    (setq dashboard-startup-banner "~/.emacs.d/emacs-dash.png")  ;; use custom image as banner
    (setq dashboard-center-content nil) ;; set to 't' for centered content
    (setq dashboard-set-footer nil)
    (setq dashboard-items '((recents . 5)
                            (agenda . 5 )
                            (bookmarks . 3)
                            (projects . 3)
                            (registers . 3)))
  :config
  (dashboard-setup-startup-hook)
  (dashboard-modify-heading-icons '((recents . "file-text")
            (bookmarks . "book"))))
#+end_src

#+RESULTS:
: t

** Dashboard in Emacsclient
This setting ensures that emacsclient always opens on *dashboard* rather than *scratch*.

#+begin_src emacs-lisp
(setq initial-buffer-choice (lambda () (get-buffer "*dashboard*")))
#+end_src

* Org

** Org mode

#+BEGIN_SRC emacs-lisp

#+END_SRC

#+BEGIN_SRC emacs-lisp
	(use-package org
	  :ensure t
	  :defer t
	  :config
	  (define-key org-mode-map
		(kbd "RET") 'org-return-indent)
	  (evil-define-key 'normal org-mode-map
		(kbd "TAB") 'org-cycle)
	  :custom
	  (org-export-with-drawers nil)
	  (org-expert-with-todo-keywords nil)
	  (org-export-with-broken-links t)
	  (org-export-with-toc nil)
	  (org-export-with-smart-quotes t))

(setq org-ellipsis "▼")
#+END_SRC

#+RESULTS:
: ▼

** Org Modern

#+BEGIN_SRC emacs-lisp
;;(use-package org-modern)
;;(with-eval-after-load 'org (global-org-modern-mode))
#+END_SRC

	#+BEGIN_SRC emacs-lisp
;;		(use-package org-modern
;;		  ;;:hook
;;		  ;;(org-mode . global-org-modern-mode)
;;		  :custom
;;		  (org-modern-keyword nil)
;;		  (org-modern-checkbox nil)
;;		  (org-modern-table nil))
;;
;;		;;(add-hook 'org-mode-hook #'org-modern-mode)
;;
;;		(setq
;;			org-auto-align-tags nil
;;			org-tags-column 0
;;			org-catch-invisible-edits 'show-and-error
;;			org-special-ctrl-a/e t
;;			org-insert-heading-respect-content t
;;			org-hide-emphasis-markers t
;;			org-pretty-entities t)
;;;;		(setq org-ellipsis "…")
;;		(setq org-ellipsis "⤵")
;;
;;		(set-face-attribute 'org-ellipsis nil :inherit 'default :box nil)
;;
;;		(with-eval-after-load 'org (global-org-modern-mode))
#+END_SRC

#+RESULTS:
: t

** Default file actions


#+BEGIN_SRC emacs-lisp
(setq org-file-apps
  (quote
    ((auto-mode . emacs)
    ("\\.x?html?\\'" . "/usr/bin/vivaldi-stable %s"))))
#+END_SRC

#+RESULTS:
: ((auto-mode . emacs) (\.x?html?\' . /usr/bin/vivaldi-stable %s))

*** 

****** 
** Org definitions

#+BEGIN_SRC emacs-lisp
;;(setq-default
;;	org-startup-folded t
;;	org-startup-indented t
;;    org-startup-with-inline-images t
;;	org-pretty-entities t
;;	org-use-sub-superscripts "{}"
;;    org-hide-emphasis-markers t
;;    org-image-actual-width '(800))
;;
;;(add-hook 'org-mode-hook
;;  (lambda ()
;;    (visual-line-mode 1)))
;;(setq org-directory "~/Documents/org"
;;  org-default-notes-file (expand-file-name "inbox.org" org-directory)
;;  org-ellipsis " ▼ "
;;  org-log-done 'time
;;  org-journal-dir "~/Documents/org/journal/"
;;  org-journal-date-format "%B %d, %Y (%A) "
;;  org-journal-file-format "%Y-%m-%d.org"
;;  org-hide-emphasis-markers t)
;;(setq org-src-preserve-indentation nil
;;  org-src-tab-acts-natively t
;;  org-edit-src-content-indentation 0
;;  org-adapt-indentation t)
;;
;;(setq org-image-actual-width 800)
#+END_SRC

#+RESULTS:
: 800

** Auto update images

#+BEGIN_SRC emacs-lisp
(add-hook 'org-babel-after-execute-hook
          (lambda ()
            (when org-inline-image-overlays
              (org-redisplay-inline-images))))
#+END_SRC

#+RESULTS:
| lambda | nil | (when org-inline-image-overlays (org-redisplay-inline-images))       |
| lambda | nil | (if org-inline-image-overlays (progn (org-redisplay-inline-images))) |

** Agenda

#+BEGIN_SRC emacs-lisp

;; start with Monday as first day of the week
(setq calendar-week-start-day 1)
;;
;;(nvmap :prefix "SPC"
;;    "a" 'org-agenda)
#+END_SRC

#+RESULTS:
: 1

** Alerts / Notifications

Shows D-Bus reminders for org files. To blacklist items, add a "PERSONAL" tag.

#+BEGIN_SRC emacs-lisp
;;    (use-package org-alert
;;  :ensure t
;;  :custom (alert-default-style 'notifications)
;;  :config
;;  (setq org-alert-interval 300
;;    org-alert-notification-title "Org Alert Reminders!")
;;  (org-alert-enable))

;; More advanced package org-wild-notifier
(use-package org-wild-notifier
        :ensure t
        :custom
        (alert-default-style 'notifications)
        (org-wild-notifier-alert-time '(1 15 30))
        (org-wild-notifier-keyword-whitelist nil)
        (org-wild-notifier-tags-blacklist '("PERSONAL"))
        (org-wild-notifier-notification-title "Org Reminder!")
        :config
        (org-wild-notifier-mode 1))
#+END_SRC

#+RESULTS:
: t

** Enabling Table of Contents
#+begin_src emacs-lisp
(use-package toc-org
    :commands toc-org-enable
    :init (add-hook 'org-mode-hook 'toc-org-enable))
#+end_src

** Org Bullets v2

#+BEGIN_SRC emacs-lisp
(require 'org-bullets)
(add-hook 'org-mode-hook (lambda () (org-bullets-mode 1)))
	;;(require 'org-bullets)
	;;(add-hook 'org-mode-hook (lambda () (org-bullets-mode 1)))
		;;(use-package org-bullets
		;;  :ensure t
		;;  :config
		;;  (add-hook 'org-mode-hook (lambda () (org-bullets-mode 1))))
#+END_SRC

#+BEGIN_SRC emacs-lisp
	;;		(use-package org-superstar
	;;		  :ensure t
	;;		  :config
	;;		  (add-hook 'org-mode-hook (lambda () (org-superstar-mode 1))))
	;;	(require 'org-superstar)
	;;	(add-hook 'org-mode-hook
	;;          (lambda ()
	;;            (org-superstar-mode 1)))
;;(require 'org-superstar)
;;(add-hook 'org-mode-hook (lambda () (org-superstar-mode 1)))
#+END_SRC

#+RESULTS:
| (lambda nil (org-superstar-mode 1)) | toc-org-enable | #[0 \300\301\302\303\304$\207 [add-hook change-major-mode-hook org-fold-show-all append local] 5] | #[0 \300\301\302\303\304$\207 [add-hook change-major-mode-hook org-babel-show-result-all append local] 5] | org-babel-result-hide-spec | org-babel-hide-all-hashes |

** Source Code Block Tag Expansion
Org-tempo is not a separate package but a module within org that can be enabled.
Org-tempo allows for '<s' followed by TAB to expand to a begin_src tag.
#+begin_src emacs-lisp
;;(with-eval-after-load 'org
;;    (require 'org-tempo))
#+end_src

#+RESULTS:

** Org Roam

TODO: Create table with commands

| COMMAND                            | DESCRIPTION       | KEYBINDING |
|------------------------------------+-------------------+------------|
| org-roam-buffer-toggle             | Toggle buffer     | SPC r t    |
| org-roam-node-find                 | Find node         | SPC r f    |
| org-roam-node-insert               | Insert node       | SPC r i    |
| org-roam-dailies-capture-today     | Capture today     | SPC r j t  |
| org-roam-dailies-goto-today        | View today        | SPC r v t  |
| org-roam-dailies-capture-yesterday | Capture yesterday | SPC r j y  |
| org-roam-dailies-goto-yesterday    | View yesterday    | SPC r v y  |
| org-roam-dailies-capture-tomorrow  | Capture tomorrow  | SPC r j m  |
| org-roam-dailies-goto-tomorrow     | View tomorrow     | SPC r v m  |

#+BEGIN_SRC emacs-lisp

	(with-system-type roamDir
		(gnu/linux "~/Documents/org/RoamNotes") ;; not the correct font yet, need to change this
		  (darwin "~/Documents/org/RoamNotes") ;; not the correct font yet, need to change this
		  (windows-nt "c:\\Users\\Jacob\\Documents\\org\\RoamNotes")
		  (t "~/org"))

	(use-package org-roam
	  :ensure t
	  :init
	  (setq org-roam-v2-ack t)
	  :custom
	  (org-roam-directory roamDir)
	  (org-roam-completion-everywhere t)
	  (org-roam-capture-templates
	   '(("d" "default" plain
		  "%?"
		  :if-new (file+head "%<%Y%m%d%H%M%S>-${slug}.org" "#+TITLE: ${title}\n")
		  :unnarrowed t)
		 ("n" "notes" plain
		  "\n%?"
		  :if-new (file+head "%<%Y%m%d%H%M%S>-${slug}.org" "#+TITLE: ${title}\n")
		  :unnarrowed t)))
	  :config
	  (org-roam-db-autosync-mode))

	(setq org-roam-dailies-capture-templates
		  '(
			("d" "Journal" entry "* %?"
			 :if-new (file+head+olp "%<%Y-%m-%d>.org"
									"#+title: %<%Y-%m-%d>\n#+filetags: %<:%Y:%B:>\n"
									("Journal")))
			("m" "Meeting" entry "* MEETING %? %U\nWith: \n"
			 :if-new (file+head+olp "%<%Y-%m-%d>.org"
									"#+title: %<%Y-%m-%d>\n#+filetags: %<%Y:%B:>\n"
									("Meeting")))
			("n" "Note" entry "* NOTE %? %U\n"
			 :if-new (file+head+olp "%<%Y-%m-%d>.org"
									"#+title: %<%Y-%m-%d>\n#+filetags: %<:%Y:%B:>\n"
									("Note")))
			("s" "Standup" entry "* STANDUP %U\n  Team: %?\n\n*** Yesterday\n\n*** Today\n\n*** Impediments\n\n"
			 :if-new (file+head+olp "%<%Y-%m-%d>.org"
									"#+title: %<%Y-%m-%d>\n#+filetags: %<%Y:%B:>\n"
									("Standup")))
			("t" "To do" entry "* TODO %?"
			 :if-new (file+head+olp "%<%Y-%m-%d>.org"
									"#+title: %<%Y-%m-%d>\n#+filetags: %<:%Y:%B:>\n"
									("To do")))))
#+END_SRC

#+RESULTS:
| d | Journal | entry | * %? | :if-new | (file+head+olp %<%Y-%m-%d>.org #+title: %<%Y-%m-%d> |

** Search org-roam

#+BEGIN_SRC emacs-lisp
;;'(use-package deadgrep)
;;'(global-set-key (kbd "<f5>") #'deadgrep)
;;'(use-package consult-ripgrep)
;;'(defun org-roam-search-args ()
;;'  "Search org-roam directory using consult-ripgrep. With live-preview." 
;;'  (let ((consult-ripgrep-args "rg --null --ignore-case --type org --line-buffered --color=never --max-columns=500 --no-heading --line-number"))
;;'    (consult-ripgrep org-roam-directory)))
;;'
;;'(defun headlong ()
;;'  "Make the current minibuffer completion exit when there is 1 candidate."
;;'  (add-hook 'after-change-functions
;;'            (lambda (&rest _)
;;'              (let* ((all (completion-all-completions
;;'                           (minibuffer-contents)
;;'                           minibuffer-completion-table
;;'                           minibuffer-completion-predicate
;;'                           (max 0 (- (point) (minibuffer-prompt-end)))))
;;'                     (last (last all)))
;;'                (when last (setcdr last nil))
;;'                (when (and all (null (cdr all)))
;;'                  (delete-minibuffer-contents)
;;'                  (insert (car all))
;;'                  (exit-minibuffer))))
;;'            nil t))
;;'
;;'(defun org-roam-search ()
;;'  (interactive)
;;'  (minibuffer-with-setup-hook #'headlong (funcall #'org-roam-search-args)))
;;'
;;'(global-set-key (kbd "<f5>") 'org-roam-search)
;;'(defun bms/org-roam-rg-search ()
;;'  "Search org-roam directory using consult-ripgrep. With live-preview."
;;'  (interactive)
;;'  (let ((consult-ripgrep-command "rg --null --ignore-case --type org --line-buffered --color=always --max-columns=500 --no-heading --line-number . -e ARG OPTS"))
;;'    (consult-ripgrep org-roam-directory))r
;;'(global-set-key (kbd "<f5>") 'bms/rg-roam-rg-search)
#+END_SRC

#+RESULTS:
: bms/org-roam-rg-search

* Other packages

** Consult

#+BEGIN_SRC emacs-lisp
;;(use-package consult)
#+END_SRC

#+RESULTS:

** Oliveti
#+BEGIN_SRC emacs-lisp
(use-package olivetti
  :demand t
  :bind
  (("<f9>" . my/distraction-free)))

(defun my/distraction-free ()
  "Distraction-free writing environment using Olivetti package."
  (interactive)
  (if (equal olivetti-mode nil)
      (progn
        (window-configuration-to-register 1)
        (delete-other-windows)
        (text-scale-set 1.5)
        (global-display-line-numbers-mode 0) 
        (olivetti-mode t))
    (progn
      (if (eq (length (window-list)) 1)
          (jump-to-register 1))
      (olivetti-mode 0)
      (global-display-line-numbers-mode 1) 
      (text-scale-set 0))))
#+END_SRC

#+RESULTS:
: my/distraction-free

** Blogging with Hugo

#+begin_src emacs-lisp
;; Github Flavored Markdown exporter for org mode
(use-package ox-gfm
  :ensure t
  :after org
  :config
  (eval-after-load "org"
    '(require 'ox-gfm nil t)))

(use-package ox-hugo
  :ensure t
  :after ox)
#+end_src

#+RESULTS:

** Magit
Complete text-based user interface to Git.
#+begin_src emacs-lisp
(use-package magit
    :commands magit-status)
#+end_src

#+RESULTS:

** Projectile
Projectile is a project interaction library for Emacs.
#+begin_src emacs-lisp
(use-package projectile
    :config
    (projectile-mode 1)
    :init
    (setq projectile-switch-project-action #'projectile-dired)
    (setq projectile-project-search-path '(("~/Projects/Github" . 1) ("~/Code/Spielerei" . 1) ("~/Code/ITnCare" . 1) ("~/Code/Rockstars")))) ;; . 1 means only search first subdirectory level for projects
;; Use Bookmarks for non git projects
#+end_src

#+RESULTS:
: t

** Company
Company is a text completion framework for Emacs. The name stands for “complete anything”.
Completion will start automatically after you type a few letters.
Use M-n and M-p to select, <tab> to complete.
#+begin_src emacs-lisp
(use-package company
    :defer 2
    :diminish
    :bind (:map company-active-map
                ("<tab>" . company-complete-selection)) ;; You can delete the :bind region to use return (default)
    :custom
    (company-begin-commands '(self-insert-command))
    (company-idle-delay 0.0)
    (company-minimum-prefix-length 1)
    (company-show-numbers t)
    (company-tooltip-align-annotations 't)
    (global-company-mode t))

(use-package company-box
    :after compan
    :diminish
    :hook (company-mode . company-box-mode))
#+end_src

#+RESULTS:

** Ivy (counsel)
Ivy, a generic completion mechanism for Emacs.
Counsel, a collection of Ivy-enhanced versions of common Emacs commands.
Ivy-rich allows us to add descriptions alongside the commands in M-x.

#+BEGIN_SRC emacs-lisp
(use-package ivy
  :diminish
  :bind (("C-s" . swiper)
         :map ivy-minibuffer-map
         ("TAB" . ivy-alt-done)
         ("C-l" . ivy-alt-done)
         ("C-j" . ivy-next-line)
         ("C-k" . ivy-previous-line)
         :map ivy-switch-buffer-map
         ("C-k" . ivy-previous-line)
         ("C-l" . ivy-done)
         ("C-d" . ivy-switch-buffer-kill)
         :map ivy-reverse-i-search-map
         ("C-k" . ivy-previous-line)
         ("C-d" . ivy-reverse-i-search-kill))
  :config
  (ivy-mode 1))

(use-package ivy-rich
  :after ivy
  :init
  (ivy-rich-mode 1))

;;(ivy-rich-modify-column
;; 'ivy-switch-buffer
;; 'ivy-rich-switch-buffer-major-mode
;; '(:width 20 :face error))

(use-package counsel
  :bind (("C-M-j" . 'counsel-switch-buffer)
         :map minibuffer-local-map
         ("C-r" . 'counsel-minibuffer-histor))
  :custom
  (counsel-linux-app-format-function #'counsel-linux-app-format-function-name-only)
  :config
  (counsel-mode 1))
#+END_SRC

#+RESULTS:
: counsel-minibuffer-histor

#+begin_src emacs-lisp
;;    (use-package counsel
;;      :after ivy
;;      :diminish
;;      :config (counsel-mode))
;;
;;    (use-package ivy
;;      :bind
;;      ;; ivy-resume resumes the last Ivy-based completion.
;;      (("C-c C-r" . ivy-resume)
;;       ("C-x B" . ivy-switch-buffer-other-window))
;;      :diminish
;;      :custom
;;      (setq ivy-use-virtual-buffers t)
;;      (setq ivy-count-format "(%d/%d) ")
;;      (setq enable-recursive-minibuffers t)
;;      :config
;;      (ivy-mode))
;;
;;    (use-package nerd-icons-ivy-rich
;;      :init
;;      (nerd-icons-ivy-rich-mode 1)
;;      (ivy-rich-mode 1))
;;
;;    (use-package ivy-rich
;;      :after ivy
;;      :init (ivy-rich-mode 1) ;; this gets us descriptions in M-x.
;;      :custom
;;      (ivy-virtual-abbreviate 'full
;;                              ivy-rich-switch-buffer-align-virtual-buffer t
;;                              ivy-rich-path-style 'abbrev)
;;      :config
;;      (ivy-set-display-transformer 'ivy-switch-buffer
;;                                   'ivy-rich-switch-buffer-transformer))
;;    (use-package counsel-projectile
;;      :config (counsel-projectile-mode))
#+end_src

** DIMINISH
This package implements hiding or abbreviation of the modeline displays (lighters) of minor-modes.
With this package installed, you can add ‘:diminish’ to any use-package block to hide that particular mode in the modeline.
#+begin_src emacs-lisp
(use-package diminish)
#+end_src

#+RESULTS:

** WHICH-KEY
Which-key is a helper utility for keychords (which key to press)
#+begin_src emacs-lisp
    (use-package which-key
      :init
      (which-key-mode 1)
      :diminish
      :config
      (setq which-key-side-window-location 'bottom
            which-key-sort-order #'which-key-key-order-alpha
            which-key-sort-uppercase-first nil
            which-key-add-column-padding 1
            which-key-max-display-columns nil
            which-key-min-display-lines 6
            which-key-side-window-slot -10
            which-key-side-window-max-height 0.25
            which-key-idle-delay 0.8
            which-key-max-description-length 25
            which-key-allow-imprecise-window-fit nil
            which-key-separator " → " ))
#+end_src

#+RESULTS:
: t

** PlantUML

#+begin_src emacs-lisp
(use-package plantuml-mode
  :ensure t
  :config
  (setq plantuml-jar-path "/usr/share/java/plantuml/plantuml.jar")
  (setq org-plantuml-jar-path "/usr/share/java/plantuml/plantuml.jar")
  (setq plantuml-default-exec-mode 'jar)
  (setq plantuml-executable-path "/usr/bin/plantuml")
  (setq plantuml-default-exec-mode 'executable)

  (add-to-list 'auto-mode-alist '("\\.plantuml\\'" . plantuml-mode))
  (add-to-list 'auto-mode-alist '("\\.pu\\'" . plantuml-mode))
  (add-to-list 'auto-mode-alist '("\\.puml\\'" . plantuml-mode))
  (setq plantuml-output-type "png"))
  (org-babel-do-load-languages 'org-babel-load-languages '((plantuml .t)))
  (with-eval-after-load 'ox-hugo
    (add-to-list 'org-hugo-special-block-type-properties '("mermaid" . (:raw t))))
#+end_src

#+RESULTS:

** Gherkin

#+begin_src emacs-lisp
;;(require 'feature-mode)
;;(add-to-list 'auto-mode-alist '("\.feature$" . feature-mode))
#+end_src

** YASnippet

#+BEGIN_SRC emacs-lisp
;; TODO: fix path, get templates
(use-package yasnippet
  :config
  (setq yas-snippet-dirs '("C:/Users/jacob/Documents/org/yasnippets"))
  (yas-global-mode 1))
#+END_SRC

#+RESULTS:
: t

** Spell checking

 Usage:
 * Use f10 to set dictionary, german or english.
 * Press f12 to check spelling in the buffer.
 * Press f11 to go to the next spelling error, ispell shows corrections that can be chosen. If not needed skip with SPC.

#+BEGIN_SRC emacs-lisp

(global-set-key (kbd "<f12>") 'flyspell-buffer)
(global-set-key (kbd "<f11>") 'flyspell-check-next-highlighted-word)
(global-set-key (kbd "<f10>") 'fd-switch-dictionary)

(setq ispell-program-name "aspell")
;;(setq ispell-local-dictionary "nl")
;;(setq ispell-current-dictionary "nl")

(defun fd-switch-dictionary()
(interactive)
(let* ((dic ispell-current-dictionary)
        (change (if (string= dic "nl") "english" "nl")))
    (ispell-change-dictionary change)
    (message "Dictionary switched from %s to %s" dic change)))

(defun flyspell-check-next-highlighted-word ()
"Custom function to spell check next highlighted word"
(interactive)
(flyspell-goto-next-error)
(ispell-word))

#+END_SRC

#+RESULTS:
: flyspell-check-next-highlighted-word

** Runtime Performance
Dial the GC threshold back down so that garbage collection happens more frequently but in less time. We also increase Read Process Output Max so emacs can read more data.
#+begin_src emacs-lisp
    ;; Make gc pauses faster by decreasing the threshold.
    (setq gc-cons-threshold (* 2 1000 1000))
    ;; Increase the amount of data which Emacs reads from the process
    (setq read-process-output-max (* 1024 1024)) ;; 1mb
#+end_src

#+RESULTS:
: 1048576

** Commenting lines

#+BEGIN_SRC emacs-lisp
(use-package evil-nerd-commenter
  :bind ("M-/" . evilnc-comment-or-uncomment-lines))
#+END_SRC

#+RESULTS:
: evilnc-comment-or-uncomment-lines

** Webjump

#+begin_src emacs-lisp
;;(use-package webjump
;;  :defer
;;  :ensure nil
;;  :bind ("C-x /" . webjump)
;;  :config
;;  (setq webjump-sites '(
;;						("Google" . [simple-query "google.com" "google.com/search?q=" ""])
;;						("GitHub" . [simple-query "github.com" "https://github.com/search?q=owner:jacobduijzer " "&type=repository"])
;;						("YouTube" . [simple-query "youtube.com/feed/subscriptions" "youtube.com/results?search_query=" ""])
;;)))
#+end_src

#+RESULTS:
: webjump

* Trying out

** Eat (terminal emulation)

Eat(Emulate A Terminal) is a terminal emulator within Emacs.
Its more portable and less overhead for users over like vterm or eshell.
We setup eat with eshell if you want to use bash, zsh etc.. Check out their git [[https://codeberg.org/akib/emacs-eat][repository]] how to do it.
#+begin_src emacs-lisp
;;(use-package eat
;;  :hook('eshell-load-hook #'eat-eshell-mode))
#+end_src


#+BEGIN_SRC emacs-lisp
	;;	(global-set-key [scroll-lock] 'ignore)
	;;	(global-set-key (kbd "<key-20>") 'ignore)
	;;    (global-set-key (kbd "<Scroll_Lock>") 'ignore)
	;;		(global-set-key (kbd "<Scroll_Lock>") 'ignore)
	;;(global-set-key (kbd "<Scroll_Lock>") 'ignore)


	;;(define-key global-map (kbd "<ScrollLock>") nil)
	;;(global-set-key (kbd "<scroll>") 'ignore)
	;;(global-set-key (kbd "<Scroll_Lock>") 'ignore)
	;;(global-set-key (kbd "<Scroll>") 'ignore)
	;;(global-set-key (kbd "<scroll-lock>") 'ignore)
	;;(global-set-key (kbd "<ScrollLock>") 'ignore)
	;;(global-set-key (kbd "Scroll_Lock") 'ignore)
	;;(global-set-key (kbd "ScrollLock") 'ignore)
	;;(global-set-key (kbd "scroll-lock") 'ignore)
	;;(global-set-key (kbd "scroll") 'ignore)

#+END_SRC

#+RESULTS:
: ignore
